/**
 * Illustrative sketches only. Diagrams of Java nets are generated by
 * ReadmeDiagramsTest (java/src/test/java/org/libpetri/adk/docs/), which
 * exports the nets the tests run (whole nets or named-transition views)
 * into dot/ and fails `mvn verify` on drift.
 *
 * Each function here builds one small PetriNet via the libpetri npm
 * package, exports it via dotExport and writes dot/sketch-<name>.dot.
 * The sketches are NOT Java nets and are NOT proved; the README captions
 * them "Illustrative". `npm run build` then renders every dot/*.dot
 * (sketches and Java exports alike) to svg/*.svg with graphviz dot.
 *
 * Conventions, matching the Java exporter's post-processing:
 * - environmentPlaces lists only real env places, so unconsumed places
 *   keep their auto "end" style and unproduced ones their "start" style;
 * - types are hidden; intervals are shown only on timed sketches, and the
 *   untimed "[0, ∞]ms" label is dropped;
 * - mid-edge "reset" labels are dropped (the bold orange style says it);
 *   "reset+out" stays;
 * - bundleResets collapses a transition's reset arcs into one orange note
 *   that names the places, as ReadmeDiagramsTest's "reset: +N places" note;
 * - the graph gets a white background, pad and nodesep 0.3 (places carry
 *   their names, so they are wide), and AND/XOR junctions get
 *   ordering=out so their branches keep the declared order;
 * - a place carries its name inside it (no xlabel), edge labels are 12 pt;
 * - a place seeded in the initial marking gets a " ●" suffix;
 * - a grey dashed note is a comment on the sketch, not net structure.
 */
import { PetriNet, Transition, place, one, outPlace, and, xor, delayed } from 'libpetri';
import { dotExport, sanitize, type DotConfig } from 'libpetri/export';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT_DIR = join(import.meta.dirname, '..', 'dot');

function write(name: string, dot: string): void {
  dot = namesInsidePlaces(dot);
  dot = dropRedundantEdgeLabels(dot);
  dot = dot.replaceAll(UNTIMED, '');
  dot = orderJunctionBranches(dot);
  dot = mustReplace(dot, /edge \[([^\]]*)fontsize=10\]/, 'edge [$1fontsize=12]', 'edge defaults');
  dot = mustReplace(dot, /^( {4})nodesep=0\.5;$/m, '$1nodesep=0.3;', 'nodesep');
  dot = mustReplace(dot, /^( {4}compound="true";)$/m, '$1\n    bgcolor="white";\n    pad="0.15";', 'graph attrs');
  writeFileSync(join(OUT_DIR, `sketch-${name}.dot`), dot);
  process.stdout.write(`wrote dot/sketch-${name}.dot\n`);
}

/** The interval libpetri prints on an untimed transition when intervals are on. */
const UNTIMED = ' [0, ∞]ms';

function baseConfig(env: string[], direction: 'LR' | 'TB' = 'LR', showIntervals = false): DotConfig {
  return {
    direction,
    showTypes: false,
    showIntervals,
    showPriority: true,
    environmentPlaces: new Set(env),
  };
}

// ---- DOT text post-processing -------------------------------------------

function mustReplace(dot: string, pattern: RegExp, replacement: string, what: string): string {
  if (!pattern.test(dot)) throw new Error(`post-process: ${what} not found`);
  return dot.replace(pattern, replacement);
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Moves each place's name from its xlabel into the node, which becomes an
 * ellipse sized to fit (end places keep a double outline). graphviz puts
 * xlabels wherever there is room, often beside another node; ReadmeDiagramsTest
 * does the same for the Java exports.
 */
function namesInsidePlaces(dot: string): string {
  const placeLine =
    /^( {4}p_\w+ \[)label="", shape="(circle|doublecircle)", (.*), width=0\.35, xlabel="([^"]*)", fixedsize="true"\];$/gm;
  let count = 0;
  const out = dot.replace(placeLine, (_m, head: string, shape: string, attrs: string, name: string) => {
    count++;
    const double = shape === 'doublecircle' ? ', peripheries=2' : '';
    return (
      `${head}label="${name}", shape="ellipse", ${attrs}, height=0.3, width=0.3, ` +
      `fixedsize="false", margin="0.08,0.03"${double}];`
    );
  });
  if (count === 0 || /xlabel=/.test(out)) throw new Error('post-process: place labels not moved');
  return out;
}

/**
 * Drops the mid-edge labels graphviz may park beside another arc: "read" on
 * read arcs (the grey dashed style says it), "reset" on reset arcs (the bold
 * orange style says it; "reset+out" stays) and an XOR branch label that
 * repeats the name of the place it points at. ReadmeDiagramsTest does the same.
 */
function dropRedundantEdgeLabels(dot: string): string {
  return dot
    .replace(/(\[[^\]]*style="dashed"[^\]]*), label="read"/g, '$1')
    .replace(/(\[[^\]]*), label="reset"/g, '$1')
    .replace(/^( {4}j_\w+ -> p_(\w+) \[[^\]]*), label="([^"]*)"/gm, (m, head: string, id: string, label: string) =>
      sanitize(label) === id ? head : m,
    );
}

/**
 * Gives every AND/XOR junction ordering=out, so graphviz lays its branches
 * out in the order the transition declares them. ReadmeDiagramsTest does the same.
 */
function orderJunctionBranches(dot: string): string {
  let count = 0;
  const out = dot.replace(/^( {4}j_\w+ \[.*)\];$/gm, (_m, head: string) => {
    count++;
    return `${head}, ordering="out"];`;
  });
  return count === 0 ? dot : out;
}

/** Adds the seed suffix (" ●" or " ●×K") to a place's label. */
function seed(dot: string, placeName: string, suffix = ' ●'): string {
  return mustReplace(
    dot,
    new RegExp(`xlabel="${escapeRe(placeName)}"`),
    `xlabel="${placeName}${suffix}"`,
    `place ${placeName}`,
  );
}

/**
 * Collapses every reset arc of a transition into one orange edge to a note
 * naming the reset places, so arcs to far places do not stretch the layout.
 * The places come from the transition itself and every arc must be found.
 * A place left with no edge is dropped. ReadmeDiagramsTest bundles the same way.
 */
function bundleResets(dot: string, t: Transition): string {
  const tid = `t_${sanitize(t.name)}`;
  const names = t.resets.map((r) => r.place.name);
  if (names.length < 2) throw new Error(`post-process: ${t.name} has ${names.length} resets; draw them instead`);
  for (const name of names) {
    const pid = `p_${sanitize(name)}`;
    dot = mustReplace(
      dot,
      new RegExp(`^ {4}${escapeRe(tid)} -> ${escapeRe(pid)} \\[color="#fd7e14"[^\\]]*\\];\\n`, 'm'),
      '',
      `reset arc ${t.name} -> ${name}`,
    );
    if (!new RegExp(`(-> ${pid} |${pid} ->)`).test(dot)) {
      dot = mustReplace(dot, new RegExp(`^ {4}${pid} \\[.*\\n`, 'm'), '', `place ${name}`);
    }
  }
  const id = `n_${sanitize(t.name)}__resets`;
  const nodeLine =
    `    ${id} [label="reset: ${names.join(', ')}", shape="note", style="filled", ` +
    `fillcolor="#fff4e6", color="#fd7e14", penwidth=1.5];\n`;
  const edgeLine = `    ${tid} -> ${id} [color="#fd7e14", style="bold", arrowhead="normal", penwidth=2];\n`;
  const end = dot.lastIndexOf('}');
  return dot.slice(0, end) + nodeLine + edgeLine + dot.slice(end);
}

/**
 * Adds a grey comment note linked to a transition by a dashed line. A
 * comment is prose about the sketch, not net structure; the legend says so.
 */
function note(dot: string, id: string, transitionName: string, text: string): string {
  const t = `t_${sanitize(transitionName)}`;
  if (!dot.includes(`${t} [`)) throw new Error(`post-process: transition ${transitionName} not found`);
  const nodeLine =
    `    ${id} [label="${text}", shape="note", style="filled", fillcolor="#ffffff", ` +
    `color="#888888", fontsize=12];\n`;
  const edgeLine = `    ${id} -> ${t} [color="#888888", style="dashed", arrowhead="none"];\n`;
  const end = dot.lastIndexOf('}');
  return dot.slice(0, end) + nodeLine + edgeLine + dot.slice(end);
}

// ============================================================
// D9. Stale-result rejection by generation stamp (README N1).
//     LATEST_GENERATION holds one token carrying the current generation;
//     BumpGeneration consumes and re-emits it with gen+1 (no reset). Each
//     commit site reads it and routes its stamped token to COMMITTED_X or
//     DISCARDED; the read is the linearization point.
// ============================================================
function sketchStaleResult(): void {
  const USER_NEW_TURN = place<unknown>('USER_NEW_TURN');
  const LATEST_GENERATION = place<unknown>('LATEST_GENERATION');
  const DISCARDED = place<unknown>('DISCARDED');
  const DISCARD_LOG = place<unknown>('DISCARD_LOG');

  const bump = Transition.builder('BumpGeneration')
    .inputs(one(USER_NEW_TURN), one(LATEST_GENERATION))
    .outputs(outPlace(LATEST_GENERATION))
    .build();

  const commitSite = (name: string, x: string) =>
    Transition.builder(name)
      .inputs(one(place<unknown>(`${x}{gen}`)))
      .read(LATEST_GENERATION)
      .outputs(xor(outPlace(place<unknown>(`COMMITTED_${x}`)), outPlace(DISCARDED)))
      .build();

  const drain = Transition.builder('DrainDiscarded')
    .inputs(one(DISCARDED))
    .outputs(outPlace(DISCARD_LOG))
    .build();

  const net = PetriNet.builder('SketchStaleResult')
    .transition(bump)
    .transition(commitSite('CommitToolResult', 'TOOL_RESULT'))
    .transition(commitSite('CommitChunk', 'CHUNK'))
    .transition(commitSite('CommitPlaceholder', 'PLACEHOLDER'))
    .transition(drain)
    .build();

  let dot = dotExport(net, baseConfig(['USER_NEW_TURN'], 'TB'));
  dot = seed(dot, 'LATEST_GENERATION');
  write('stale-result', dot);
}

// ============================================================
// D11. Tiered SLA escalation ladder (README G5). Exactly one rung token
//      exists per turn and every answer consumes it, so an answer
//      cancels escalation and at most one answer is emitted. Sla_Start
//      resets the per-turn markers ANSWERED and DISCARDED.
// ============================================================
function sketchTieredSlaLadder(): void {
  const REQUEST = place<unknown>('REQUEST');
  const PRIMARY_CALL = place<unknown>('PRIMARY_CALL');
  const PRIMARY_DONE = place<unknown>('PRIMARY_DONE');
  const FALLBACK_CALL = place<unknown>('FALLBACK_CALL');
  const FALLBACK_DONE = place<unknown>('FALLBACK_DONE');
  const RUNG_1 = place<unknown>('RUNG_1');
  const RUNG_2 = place<unknown>('RUNG_2');
  const RUNG_3 = place<unknown>('RUNG_3');
  const EVENT_OUT = place<unknown>('EVENT_OUT');
  const ANSWERED = place<unknown>('ANSWERED');
  const DISCARDED = place<unknown>('DISCARDED');

  const answer = () => and(outPlace(EVENT_OUT), outPlace(ANSWERED));

  const start = Transition.builder('Sla_Start')
    .inputs(one(REQUEST))
    .resets(ANSWERED, DISCARDED)
    .outputs(and(outPlace(PRIMARY_CALL), outPlace(RUNG_1)))
    .build();
  const callPrimary = Transition.builder('Sla_CallPrimary')
    .inputs(one(PRIMARY_CALL))
    .outputs(outPlace(PRIMARY_DONE))
    .build();
  const answerPrimary = Transition.builder('Sla_AnswerPrimary')
    .inputs(one(PRIMARY_DONE), one(RUNG_1))
    .outputs(answer())
    .priority(10)
    .build();
  const escalate1 = Transition.builder('Sla_Escalate1')
    .inputs(one(RUNG_1))
    .outputs(and(outPlace(RUNG_2), outPlace(FALLBACK_CALL)))
    .timing(delayed(2000))
    .build();
  const callFallback = Transition.builder('Sla_CallFallback')
    .inputs(one(FALLBACK_CALL))
    .outputs(outPlace(FALLBACK_DONE))
    .build();
  const answerPrimaryLate = Transition.builder('Sla_AnswerPrimaryLate')
    .inputs(one(PRIMARY_DONE), one(RUNG_2))
    .outputs(answer())
    .priority(10)
    .build();
  const answerFallback = Transition.builder('Sla_AnswerFallback')
    .inputs(one(FALLBACK_DONE), one(RUNG_2))
    .outputs(answer())
    .priority(5)
    .build();
  const escalate2 = Transition.builder('Sla_Escalate2')
    .inputs(one(RUNG_2))
    .outputs(outPlace(RUNG_3))
    .timing(delayed(3000))
    .build();
  const answerCached = Transition.builder('Sla_AnswerCached')
    .inputs(one(RUNG_3))
    .outputs(answer())
    .build();
  const discardPrimary = Transition.builder('Sla_DiscardPrimary')
    .inputs(one(PRIMARY_DONE))
    .read(ANSWERED)
    .outputs(outPlace(DISCARDED))
    .priority(-10)
    .build();
  const discardFallback = Transition.builder('Sla_DiscardFallback')
    .inputs(one(FALLBACK_DONE))
    .read(ANSWERED)
    .outputs(outPlace(DISCARDED))
    .priority(-10)
    .build();

  const net = PetriNet.builder('SketchTieredSlaLadder')
    .transition(start)
    .transition(callPrimary)
    .transition(answerPrimary)
    .transition(escalate1)
    .transition(callFallback)
    .transition(answerPrimaryLate)
    .transition(answerFallback)
    .transition(escalate2)
    .transition(answerCached)
    .transition(discardPrimary)
    .transition(discardFallback)
    .build();

  // The only timed sketch: it shows the escalation delays on the transitions.
  let dot = dotExport(net, baseConfig(['REQUEST'], 'TB', true));
  dot = bundleResets(dot, start);
  write('tiered-sla-ladder', dot);
}

// ============================================================
// D8. Variable-N fan-out with an orthogonal monitor (README N2). Spawn's
//     action emits N JOB tokens and N JOB_PENDING tokens; Finish waits
//     for JOB_PENDING to drain (inhibitor) and returns the batch permit.
// ============================================================
function sketchFanoutMonitor(): void {
  const SEARCH_REQUEST = place<unknown>('SEARCH_REQUEST');
  const OBSERVE = place<unknown>('OBSERVE');
  const BATCH_PERMIT = place<unknown>('BATCH_PERMIT');
  const JOB = place<unknown>('JOB');
  const JOB_PENDING = place<unknown>('JOB_PENDING');
  const BATCH_OPEN = place<unknown>('BATCH_OPEN');
  const COLLECTOR = place<unknown>('COLLECTOR');
  const RESULT = place<unknown>('RESULT');
  const SNAPSHOT = place<unknown>('SNAPSHOT');
  const SELECTION_READY = place<unknown>('SELECTION_READY');

  const spawn = Transition.builder('Spawn')
    .inputs(one(SEARCH_REQUEST), one(BATCH_PERMIT))
    .outputs(and(outPlace(JOB), outPlace(JOB_PENDING), outPlace(BATCH_OPEN), outPlace(COLLECTOR)))
    .build();
  const worker = Transition.builder('Worker')
    .inputs(one(JOB))
    .outputs(outPlace(RESULT))
    .build();
  const collect = Transition.builder('Collect')
    .inputs(one(RESULT), one(JOB_PENDING), one(COLLECTOR))
    .outputs(outPlace(COLLECTOR))
    .build();
  const orthogonalRead = Transition.builder('OrthogonalRead')
    .inputs(one(OBSERVE))
    .read(COLLECTOR)
    .outputs(outPlace(SNAPSHOT))
    .build();
  const finish = Transition.builder('Finish')
    .inputs(one(BATCH_OPEN), one(COLLECTOR))
    .inhibitor(JOB_PENDING)
    .outputs(and(outPlace(SELECTION_READY), outPlace(BATCH_PERMIT)))
    .priority(-10)
    .build();

  const net = PetriNet.builder('SketchFanoutMonitor')
    .transition(spawn)
    .transition(worker)
    .transition(collect)
    .transition(orthogonalRead)
    .transition(finish)
    .build();

  let dot = dotExport(net, baseConfig(['SEARCH_REQUEST', 'OBSERVE'], 'TB'));
  dot = seed(dot, 'BATCH_PERMIT');
  dot = note(dot, 'n_Spawn_emits', 'Spawn', 'action emits N×JOB + N×JOB_PENDING');
  write('fanout-monitor', dot);
}

sketchStaleResult();
sketchTieredSlaLadder();
sketchFanoutMonitor();
process.stdout.write('done.\n');
